### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by o-coder-s** [Palexer/image-viewer#10]
I tried to open picture with 10Mb size around 4K resolution and it took **1GB**  in RAM which is Huge. 
![image](https://user-images.githubusercontent.com/46224889/117834066-c66b4e80-b26e-11eb-8379-dce4e80be7e1.png)

**Comment by Palexer** [comment]
Because Go is a garbage collected language, I can't really improve memory management. I tried opening a 10Mb image myself and it used 228Mb of RAM. Did you maybe open a folder with a lot of images and switched between them? This would probably use more memory. Maybe you could try opening a few other images of about the same size and see if they're also using a lot of memory.

**Comment by bikedel** [comment]
I often load files > 10mb  < 20mb  Cannon 5D mkII. Some folders have over 2000 images.

If I skip between large images my memory also goes to +- 1Gb memory.


I am currently only using Fyne for desktop. Loading large images is slow.


I can load >12 images >12mb each, resize them and display them as thumbnails and this takes about 300mb memory. ie: I load the images and resize to 300 LanczosResampling and then display.

So if you need to keep the memory low and resizing is ok maybe that will help?


If you could tell me what your use case is I could look at other options.
