### ISSUE TITLE
 cropping -annotations 

### ISSUE THREAD

**Issue by bikedel** [Palexer/image-viewer#7]
hello
 
is this project going forward? May I ask in what direction?

Could you add cropping / annotations ?

Thanks

**Comment by Palexer** [comment]
Hey,
sure, I'll continue working on it. I am happy that there is interest in the project. But please keep in mind, that I don't always have that much time for it, since it is just a little side project and there are other projects I work on too. There is an image resize feature added in commit 69ad5fb, but it's not really a cropping feature. What do you exactly mean with annotations? Tooltips like [this](https://www.netdip.com/fileadmin/user_upload/GNU_Image_Manipulation_Program_019.png) one? If that's the case, I have to see if this is possible with the Fyne toolkit. Also, always feel free to submit a pull request if you want to!

**Comment by bikedel** [comment]
Hi.

Thanks for the response!  


I would like to be able to draw a bounding box around an object in the image. 

With the bounding box co-ordinates and a label  I can save the data to a csv file or database… or simply crop the image. Annotations are used for training datasets for GAN’s.

**Comment by Palexer** [comment]
Ok, so you probably know more about this topic than I do. Do have an idea of how to draw the box around an object in the image?

**Comment by bikedel** [comment]
no I am new to both Fyne and golang
I was hoping you knew how to
